version: '3.8'

services:
  db:
    image: postgres:15
    container_name: npu_postgres
    restart: always
    environment:
      POSTGRES_DB: npu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: npu_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_CONN: "dbname=npu_db user=postgres password=yourpassword host=db"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
